language: php
php:
  - 7.0
  - nightly

before_script:
  - git clone https://github.com/tideways/php-profiler-extension.git
  - cd php-profiler-extension && phpize && ./configure && make && make install && cd ..
  - echo "extension=tideways.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "tideways.auto_prepend_library=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - composer install --prefer-dist --dev
